##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should
# be placed in this file
#
##############################################################################
##############################################################################

name: PR target workflow
on:
  pull_request_target:

jobs:
  PR-Target:
    name: Pull Request Target
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo $GITHUB_WORKSPACE
      - name: Test 2
        run: echo `ls ${{GITHUB_WORKSPACE}}`
      - name: Add the PR Review Policy as a comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ${{GITHUB_WORKSPACE}}/.github/PR_REVIEW_POLICY.md
